### ISSUE TITLE
Include pipeline version in report text

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_generate_variant_workbook#25]
Things to consider:
How best to record this for re-analysis, when the version used to generate the data may differ from the current version use to generate the report.
How to give a single version when the pipeline comprises multiple workflows, each with their own version

**Comment by jethror1** [comment]
@mattgarner can this now be closed since we record job/workflow IDs in the output Excel, and annotation is re-run in the same workflow?
